from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

class AnalyticsEventCreate(BaseModel):
    """Schema for creating a single analytics event"""
    module_id: str
    question_id: str
    question_type: str
    difficulty_level: int
    is_correct: bool
    duration_ms: int = Field(..., ge=0)
    hesitation_ms: int = Field(default=0, ge=0)
    # Timestamp is server-generated by default, but can be provided for offline sync
    timestamp: Optional[datetime] = None

class AnalyticsEventResponse(BaseModel):
    """Schema for analytics event response"""
    id: str
    child_id: str
    module_id: str
    is_correct: bool
    duration_ms: int
    timestamp: datetime
